### ISSUE TITLE
Config object should dynamically set directory module name

### ISSUE THREAD

**Issue by adorton-adobe** [adorton-adobe/user-sync.py#2]
Should be based on the label in the main config.

Given this example:

```yaml
directory:
  connectors:
    ldap: C:\Users\adorton\projects\user-sync.py\config\connector-ldap.yml
```

The directory module name `user_sync.connector.directory_ldap` would be set in the config object.
